language: ruby
env:
  matrix:
  - FORMATS=human,json HUMAN_OUTPUT=system_info.txt JSON_OUTPUT=system_info.json 
  - FORMATS=human,json HUMAN_OUTPUT=system_info.txt JSON_OUTPUT=system_info.json COMMANDS_FILE=mini_commands.yml
script:
- bundle exec bin/system_info "$(curl https://api.github.com/repos/travis-ci/travis-cookbooks/git/refs/heads/master 2>/dev/null | awk -F\\\" '/sha/ {print $4}' | cut -c 1-7)"
- grep 'Cookbooks Version' system_info.txt
